import type { Order, Rider, Customer } from "@/types/orders";

// ============================================
// 6 Sample Delivery Fleet Riders (Faisalabad)
// ============================================
export const SAMPLE_RIDERS: Rider[] = [
  {
    id: "rider-01",
    name: "Ali Raza",
    phone: "0301-4458921",
    vehicleType: "bike",
    vehicleNumber: "FSD-8821 (Honda 125)",
    status: "on-trip",
    currentOrderId: "order-1040",
    primaryZone: "Kohinoor City & Jaranwala Rd",
    completedDeliveriesToday: 11,
    totalDeliveries: 480,
    rating: 4.9,
  },
  {
    id: "rider-02",
    name: "Usman Tariq",
    phone: "0321-7789012",
    vehicleType: "bike",
    vehicleNumber: "FSD-4190 (Yamaha YBR)",
    status: "available",
    currentOrderId: null,
    primaryZone: "Susan Road & Madina Town",
    completedDeliveriesToday: 14,
    totalDeliveries: 620,
    rating: 4.8,
  },
  {
    id: "rider-03",
    name: "Kashif Mehmood",
    phone: "0305-6612984",
    vehicleType: "bike",
    vehicleNumber: "FSD-1934 (Honda CD70)",
    status: "on-trip",
    currentOrderId: "order-1037",
    primaryZone: "Madina Town & Canal Expressway",
    completedDeliveriesToday: 8,
    totalDeliveries: 340,
    rating: 4.7,
  },
  {
    id: "rider-04",
    name: "Farhan Saeed",
    phone: "0332-9182374",
    vehicleType: "bike",
    vehicleNumber: "FSD-5520 (United 100)",
    status: "available",
    currentOrderId: null,
    primaryZone: "Susan Road Sector B",
    completedDeliveriesToday: 9,
    totalDeliveries: 290,
    rating: 4.8,
  },
  {
    id: "rider-05",
    name: "Bilal Butt",
    phone: "0314-5519283",
    vehicleType: "bike",
    vehicleNumber: "FSD-7312 (Honda 125)",
    status: "available",
    currentOrderId: null,
    primaryZone: "D-Ground & Peoples Colony",
    completedDeliveriesToday: 12,
    totalDeliveries: 510,
    rating: 4.9,
  },
  {
    id: "rider-06",
    name: "Zeeshan Khan",
    phone: "0323-8819234",
    vehicleType: "bike",
    vehicleNumber: "FSD-9011 (Suzuki GS150)",
    status: "on-trip",
    currentOrderId: "order-1036",
    primaryZone: "Eden Valley & Susan Rd",
    completedDeliveriesToday: 10,
    totalDeliveries: 415,
    rating: 4.8,
  },
];

// Helper to generate dynamic ISO timestamps relative to now
const getRelativeISO = (minutesAgo: number): string => {
  const date = new Date(Date.now() - minutesAgo * 60 * 1000);
  return date.toISOString();
};

// ============================================
// 15 Sample Orders Covering All Scenarios
// ============================================
export const SAMPLE_ORDERS: Order[] = [
  // 1. PENDING (Website delivery order, just arrived)
  {
    id: "order-1045",
    orderNumber: "#PK-1045",
    customerName: "Mohsin Javed",
    phone: "0304-9871234",
    orderType: "delivery",
    deliveryAddress: {
      street: "Street 8, Main Boulevard",
      area: "Kohinoor City",
      city: "Faisalabad",
      houseNumber: "House 24-B",
      landmark: "Near Gloria Jean's Coffees",
      fullAddress: "House 24-B, Street 8, Main Boulevard, Kohinoor City, Faisalabad",
    },
    status: "pending",
    items: [
      {
        id: "item-1",
        menuItemId: "pizza-kitchen-special",
        name: "Pizza Kitchen Special Pizza",
        price: 1790,
        quantity: 1,
        size: "Large",
        crust: "Thick Crust",
        customizations: ["Extra Mozzarella Cheese", "Jalapenos"],
        notes: "Please make it crispy on the edges.",
        itemTotal: 1790,
      },
      {
        id: "item-2",
        menuItemId: "garlic-bread-supreme",
        name: "Garlic Bread Supreme",
        price: 450,
        quantity: 1,
        itemTotal: 450,
      },
      {
        id: "item-3",
        menuItemId: "cold-coffee",
        name: "Cold Coffee",
        price: 450,
        quantity: 2,
        itemTotal: 900,
      },
    ],
    subtotal: 3140,
    deliveryFee: 150,
    discount: 0,
    total: 3290,
    source: "website",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "cash",
    paymentStatus: "pending",
    notes: "Ring doorbell twice, please do not honk.",
    createdAt: getRelativeISO(3),
    updatedAt: getRelativeISO(3),
  },

  // 2. PENDING (WhatsApp order, pending cashier confirmation)
  {
    id: "order-1044",
    orderNumber: "#PK-1044",
    customerName: "Zainab Chaudhry",
    phone: "0322-5544332",
    orderType: "takeaway",
    status: "pending",
    items: [
      {
        id: "item-4",
        menuItemId: "chicken-tikka",
        name: "Chicken Tikka Pizza",
        price: 1540,
        quantity: 1,
        size: "Medium",
        crust: "Round Crust",
        itemTotal: 1540,
      },
      {
        id: "item-5",
        menuItemId: "hot-wings",
        name: "Oven Baked Hot Wings (6 pcs)",
        price: 350,
        quantity: 1,
        itemTotal: 350,
      },
    ],
    subtotal: 1890,
    deliveryFee: 0,
    discount: 100,
    total: 1790,
    source: "whatsapp",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "easypaisa",
    paymentStatus: "paid",
    notes: "Customer will pickup in 25 mins by car.",
    createdAt: getRelativeISO(7),
    updatedAt: getRelativeISO(5),
  },

  // 3. PREPARING (In Oven - Delivery order from WhatsApp)
  {
    id: "order-1042",
    orderNumber: "#PK-1042",
    customerName: "Hamza Tariq",
    phone: "0302-8472910",
    orderType: "delivery",
    deliveryAddress: {
      street: "Canal Road, Green Town",
      area: "Susan Road Sector A",
      city: "Faisalabad",
      houseNumber: "House 12",
      landmark: "Near Allied Hospital Gate 2",
      fullAddress: "House 12, Street 4, Susan Road Sector A, Faisalabad",
    },
    status: "preparing",
    items: [
      {
        id: "item-6",
        menuItemId: "super-supreme",
        name: "Super Supreme Pizza",
        price: 1790,
        quantity: 1,
        size: "Large",
        crust: "Thick Crust",
        customizations: ["Extra Olives", "Extra Mushrooms"],
        notes: "Heavy cheese topping requested.",
        itemTotal: 1790,
      },
      {
        id: "item-7",
        menuItemId: "hot-wings",
        name: "Oven Baked Hot Wings",
        price: 350,
        quantity: 1,
        size: "6 Pcs",
        itemTotal: 350,
      },
    ],
    subtotal: 2140,
    deliveryFee: 150,
    discount: 150,
    total: 2140,
    source: "whatsapp",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "cash",
    paymentStatus: "pending",
    notes: "Call when rider leaves Susan Rd branch.",
    createdAt: getRelativeISO(12),
    updatedAt: getRelativeISO(8),
  },

  // 4. PREPARING (Dine-In Table 4 - Counter POS)
  {
    id: "order-1043",
    orderNumber: "#PK-1043",
    customerName: "Tariq Mehmood (Table 4)",
    phone: "0311-6623819",
    orderType: "dine-in",
    tableNumber: "Table 4 (Family Corner)",
    status: "preparing",
    items: [
      {
        id: "item-8",
        menuItemId: "fettuccine-alfredo",
        name: "Fettuccine Alfredo Pasta",
        price: 899,
        quantity: 2,
        notes: "Serve with extra parmesan cheese and chili flakes on the side.",
        itemTotal: 1798,
      },
      {
        id: "item-9",
        menuItemId: "garlic-bread-supreme",
        name: "Garlic Bread Supreme",
        price: 450,
        quantity: 1,
        itemTotal: 450,
      },
    ],
    subtotal: 2248,
    deliveryFee: 0,
    discount: 0,
    total: 2248,
    source: "pos",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "card",
    paymentStatus: "paid",
    notes: "Serve garlic bread as starter first.",
    createdAt: getRelativeISO(14),
    updatedAt: getRelativeISO(10),
  },

  // 5. PREPARING (Delivery - Web order)
  {
    id: "order-1037",
    orderNumber: "#PK-1037",
    customerName: "Khurram Shahzad",
    phone: "0300-9812734",
    orderType: "delivery",
    deliveryAddress: {
      street: "Sector B, Main Boulevard",
      area: "Madina Town",
      city: "Faisalabad",
      houseNumber: "Plot 88",
      landmark: "Near Madina Central Mosque",
      fullAddress: "Plot 88, Sector B, Madina Town, Faisalabad",
    },
    status: "preparing",
    items: [
      {
        id: "item-10",
        menuItemId: "chicken-fajita",
        name: "Chicken Fajita Pizza",
        price: 1540,
        quantity: 2,
        size: "Medium",
        crust: "Round Crust",
        customizations: ["1x Extra Spicy, 1x Mild"],
        itemTotal: 3080,
      },
      {
        id: "item-11",
        menuItemId: "potato-wedges",
        name: "Potato Wedges (Large)",
        price: 650,
        quantity: 1,
        notes: "Include 2 garlic mayo dips.",
        itemTotal: 650,
      },
    ],
    subtotal: 3730,
    deliveryFee: 150,
    discount: 0,
    total: 3880,
    source: "website",
    riderAssigned: SAMPLE_RIDERS[2], // Kashif
    riderId: "rider-03",
    paymentMethod: "cash",
    paymentStatus: "pending",
    notes: "Rider Kashif assigned for Madina Town run.",
    createdAt: getRelativeISO(18),
    updatedAt: getRelativeISO(12),
  },

  // 6. READY (Counter Takeaway order)
  {
    id: "order-1041",
    orderNumber: "#PK-1041",
    customerName: "Ayesha Malik",
    phone: "0321-9923841",
    orderType: "takeaway",
    status: "ready",
    items: [
      {
        id: "item-12",
        menuItemId: "chicken-tikka",
        name: "Chicken Tikka Pizza",
        price: 1540,
        quantity: 1,
        size: "Medium",
        crust: "Round Crust",
        itemTotal: 1540,
      },
      {
        id: "item-13",
        menuItemId: "garlic-bread-supreme",
        name: "Garlic Bread Supreme",
        price: 450,
        quantity: 1,
        itemTotal: 450,
      },
    ],
    subtotal: 1990,
    deliveryFee: 0,
    discount: 0,
    total: 1990,
    source: "pos",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "cash",
    paymentStatus: "paid",
    notes: "Hot in packaging box at pickup counter.",
    createdAt: getRelativeISO(22),
    updatedAt: getRelativeISO(4),
  },

  // 7. READY (Delivery order packed, waiting for rider pickup)
  {
    id: "order-1038-R",
    orderNumber: "#PK-1038",
    customerName: "Sarmad Ali",
    phone: "0345-7192834",
    orderType: "delivery",
    deliveryAddress: {
      street: "Eden Valley Commercial Zone",
      area: "Eden Valley",
      city: "Faisalabad",
      houseNumber: "House 51-C",
      landmark: "Opposite Eden Club",
      fullAddress: "House 51-C, Eden Valley, Faisalabad",
    },
    status: "ready",
    items: [
      {
        id: "item-14",
        menuItemId: "malai-boti",
        name: "Malai Boti Pizza",
        price: 1790,
        quantity: 1,
        size: "Large",
        crust: "Thick Crust",
        itemTotal: 1790,
      },
      {
        id: "item-15",
        menuItemId: "special-platter",
        name: "Special Platter",
        price: 990,
        quantity: 1,
        itemTotal: 990,
      },
    ],
    subtotal: 2780,
    deliveryFee: 150,
    discount: 200,
    total: 2730,
    source: "whatsapp",
    riderAssigned: SAMPLE_RIDERS[1], // Usman
    riderId: "rider-02",
    paymentMethod: "jazzcash",
    paymentStatus: "paid",
    notes: "Packed in thermal heat bag.",
    createdAt: getRelativeISO(26),
    updatedAt: getRelativeISO(5),
  },

  // 8. OUT FOR DELIVERY (Rider Ali Raza on trip)
  {
    id: "order-1040",
    orderNumber: "#PK-1040",
    customerName: "Bilal Chaudhry",
    phone: "0333-5128472",
    orderType: "delivery",
    deliveryAddress: {
      street: "Main Susan Road",
      area: "Susan Road",
      city: "Faisalabad",
      houseNumber: "Plaza 4B, 2nd Floor",
      landmark: "Above Standard Chartered Bank",
      fullAddress: "Plaza 4B, 2nd Floor, Main Susan Road, Faisalabad",
    },
    status: "out-for-delivery",
    items: [
      {
        id: "item-16",
        menuItemId: "fettuccine-alfredo",
        name: "Fettuccine Alfredo",
        price: 899,
        quantity: 2,
        itemTotal: 1798,
      },
      {
        id: "item-17",
        menuItemId: "brownie-sundae",
        name: "Brownie Sundae",
        price: 399,
        quantity: 1,
        itemTotal: 399,
      },
    ],
    subtotal: 2197,
    deliveryFee: 150,
    discount: 0,
    total: 2347,
    source: "website",
    riderAssigned: SAMPLE_RIDERS[0], // Ali Raza
    riderId: "rider-01",
    paymentMethod: "online",
    paymentStatus: "paid",
    notes: "Rider Ali Raza dispatched at 12:48 PM.",
    createdAt: getRelativeISO(32),
    updatedAt: getRelativeISO(10),
  },

  // 9. OUT FOR DELIVERY (Rider Zeeshan on trip)
  {
    id: "order-1036",
    orderNumber: "#PK-1036",
    customerName: "Sara Munir",
    phone: "0323-8819200",
    orderType: "delivery",
    deliveryAddress: {
      street: "Civil Lines, Officers Colony 1",
      area: "D-Ground",
      city: "Faisalabad",
      houseNumber: "Bungalow 7",
      landmark: "Near D-Ground Commercial Market",
      fullAddress: "Bungalow 7, Officers Colony 1, D-Ground, Faisalabad",
    },
    status: "out-for-delivery",
    items: [
      {
        id: "item-18",
        menuItemId: "vegi-lover",
        name: "Vegi Lover Pizza",
        price: 1540,
        quantity: 1,
        size: "Medium",
        crust: "Thin Crust",
        itemTotal: 1540,
      },
      {
        id: "item-19",
        menuItemId: "salad",
        name: "Fresh Salad (Full)",
        price: 799,
        quantity: 1,
        itemTotal: 799,
      },
    ],
    subtotal: 2339,
    deliveryFee: 150,
    discount: 0,
    total: 2489,
    source: "website",
    riderAssigned: SAMPLE_RIDERS[5], // Zeeshan Khan
    riderId: "rider-06",
    paymentMethod: "jazzcash",
    paymentStatus: "paid",
    notes: "Dispatched with cutlery and napkins.",
    createdAt: getRelativeISO(38),
    updatedAt: getRelativeISO(14),
  },

  // 10. COMPLETED (Dine-In Table 1)
  {
    id: "order-1034",
    orderNumber: "#PK-1034",
    customerName: "Dr. Usman Farooq",
    phone: "0312-4458921",
    orderType: "dine-in",
    tableNumber: "Table 1 (Window Side)",
    status: "completed",
    items: [
      {
        id: "item-20",
        menuItemId: "bbq-platter",
        name: "BBQ Platter",
        price: 1090,
        quantity: 1,
        itemTotal: 1090,
      },
      {
        id: "item-21",
        menuItemId: "cappuccino",
        name: "Cappuccino",
        price: 380,
        quantity: 2,
        itemTotal: 760,
      },
    ],
    subtotal: 1850,
    deliveryFee: 0,
    discount: 0,
    total: 1850,
    source: "pos",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "cash",
    paymentStatus: "paid",
    notes: "Completed & receipt printed.",
    createdAt: getRelativeISO(65),
    updatedAt: getRelativeISO(25),
  },

  // 11. COMPLETED (Delivery to Susan Rd)
  {
    id: "order-1033",
    orderNumber: "#PK-1033",
    customerName: "Hassan Raza",
    phone: "0300-8472911",
    orderType: "delivery",
    deliveryAddress: {
      street: "Street 2, Susan Road",
      area: "Susan Road",
      city: "Faisalabad",
      houseNumber: "House 91",
      landmark: "Near Pizza Kitchen",
      fullAddress: "House 91, Street 2, Susan Road, Faisalabad",
    },
    status: "completed",
    items: [
      {
        id: "item-22",
        menuItemId: "chicken-tikka",
        name: "Chicken Tikka Pizza (Large)",
        price: 2399,
        quantity: 1,
        size: "Large",
        itemTotal: 2399,
      },
      {
        id: "item-23",
        menuItemId: "peri-peri-wings",
        name: "Peri Peri Wings (6 pcs)",
        price: 430,
        quantity: 1,
        itemTotal: 430,
      },
    ],
    subtotal: 2829,
    deliveryFee: 150,
    discount: 200,
    total: 2779,
    source: "website",
    riderAssigned: SAMPLE_RIDERS[0],
    riderId: "rider-01",
    paymentMethod: "cash",
    paymentStatus: "paid",
    notes: "Delivered in 21 mins by Ali Raza.",
    createdAt: getRelativeISO(85),
    updatedAt: getRelativeISO(60),
  },

  // 12. COMPLETED (Takeaway POS Order)
  {
    id: "order-1031",
    orderNumber: "#PK-1031",
    customerName: "Mohsin Ali",
    phone: "0313-9912834",
    orderType: "takeaway",
    status: "completed",
    items: [
      {
        id: "item-24",
        menuItemId: "lasagne",
        name: "Lasagne",
        price: 899,
        quantity: 1,
        itemTotal: 899,
      },
    ],
    subtotal: 899,
    deliveryFee: 0,
    discount: 0,
    total: 899,
    source: "pos",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "easypaisa",
    paymentStatus: "paid",
    notes: "Pickup completed at counter.",
    createdAt: getRelativeISO(110),
    updatedAt: getRelativeISO(95),
  },

  // 13. COMPLETED (Family Dine-In Table 8)
  {
    id: "order-1030",
    orderNumber: "#PK-1030",
    customerName: "Sheikh Nadeem (Table 8)",
    phone: "0321-1234567",
    orderType: "dine-in",
    tableNumber: "Table 8 (Family Hall)",
    status: "completed",
    items: [
      {
        id: "item-25",
        menuItemId: "square-large",
        name: "Square Pizza Large",
        price: 2599,
        quantity: 2,
        size: "Large (Square)",
        itemTotal: 5198,
      },
      {
        id: "item-26",
        menuItemId: "milkshake-icecream",
        name: "Milkshake with Icecream",
        price: 450,
        quantity: 4,
        itemTotal: 1800,
      },
    ],
    subtotal: 6998,
    deliveryFee: 0,
    discount: 500,
    total: 6498,
    source: "pos",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "card",
    paymentStatus: "paid",
    notes: "VIP guest discount applied.",
    createdAt: getRelativeISO(140),
    updatedAt: getRelativeISO(90),
  },

  // 14. CANCELLED (Customer duplicate order request)
  {
    id: "order-1039",
    orderNumber: "#PK-1039",
    customerName: "Zubair Ahmed",
    phone: "0300-7629104",
    orderType: "delivery",
    deliveryAddress: {
      street: "Gulberg Road",
      area: "Peoples Colony 1",
      city: "Faisalabad",
      houseNumber: "House 109",
      landmark: "Near Chenab Club",
      fullAddress: "House 109, Gulberg Road, Peoples Colony 1, Faisalabad",
    },
    status: "cancelled",
    items: [
      {
        id: "item-27",
        menuItemId: "malai-boti",
        name: "Malai Boti Pizza (XL)",
        price: 2650,
        quantity: 1,
        size: "XL",
        itemTotal: 2650,
      },
    ],
    subtotal: 2650,
    deliveryFee: 150,
    discount: 0,
    total: 2800,
    source: "whatsapp",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "cash",
    paymentStatus: "refunded",
    notes: "Customer cancelled before baking started.",
    cancelReason: "Customer placed duplicate order by mistake on WhatsApp.",
    createdAt: getRelativeISO(45),
    updatedAt: getRelativeISO(40),
  },

  // 15. CANCELLED (Address mismatch on online order)
  {
    id: "order-1032",
    orderNumber: "#PK-1032",
    customerName: "Noman Sadiq",
    phone: "0322-6712399",
    orderType: "delivery",
    deliveryAddress: {
      street: "Sargodha Road",
      area: "Millat Town",
      city: "Faisalabad",
      houseNumber: "Shop 14",
      landmark: "Out of Susan Rd delivery radius",
      fullAddress: "Shop 14, Sargodha Road, Millat Town, Faisalabad",
    },
    status: "cancelled",
    items: [
      {
        id: "item-28",
        menuItemId: "fettuccine-alfredo",
        name: "Fettuccine Alfredo",
        price: 899,
        quantity: 2,
        itemTotal: 1798,
      },
      {
        id: "item-29",
        menuItemId: "garlic-mushrooms",
        name: "Garlic Mushrooms",
        price: 375,
        quantity: 1,
        itemTotal: 375,
      },
    ],
    subtotal: 2173,
    deliveryFee: 150,
    discount: 0,
    total: 2323,
    source: "website",
    riderAssigned: null,
    riderId: null,
    paymentMethod: "online",
    paymentStatus: "refunded",
    notes: "Out of delivery area. Customer refunded.",
    cancelReason: "Delivery location (Millat Town) is outside the 30-min delivery zone from Susan Road branch.",
    createdAt: getRelativeISO(160),
    updatedAt: getRelativeISO(150),
  },
];
